services:
  postgresDev:
    image: postgres:18
    environment:
      POSTGRES_DB: tv_tracker_dev
      POSTGRES_USER: tv_tracker
      POSTGRES_PASSWORD: tv_tracker_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql
    networks:
      - dev
    command: >
      postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB -c shared_buffers=256MB

volumes:
  postgres_dev_data:
    name: tv-tracker-dev-db

networks:
  dev:
    name: tv-tracker-dev
    driver: bridge
