name: OpenTelemetry Export Trace

on:
  workflow_run:
    workflows:
      [
        "âŒ Delete Episode",
        "ğŸ”„ Force Episode Update",
        "âŒ Remove inexisting episode links",
        "ğŸš€ Test",
        "ğŸ†• Update",
      ]
    types: [completed]

jobs:
  otel-export-trace:
    if: always()
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    steps:
      - name: Export Workflow Trace
        uses: inception-health/otel-export-trace-action@b70e5a1e4cc4764bbbaeb963f8952b8d3d1529ba
        with:
          otlpEndpoint: ${{ secrets.OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.OTLP_HEADERS }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
